# Generated by Django 6.0.1 on 2026-01-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_company_options_remove_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_bpcode',
        ),
        migrations.AddField(
            model_name='company',
            name='company_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_bfaxpcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='defcompany',
            field=models.BooleanField(default=False),
        ),
    ]
