# Generated by Django 6.0.1 on 2026-01-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_company_company_bpcode_company_company_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_bfaxpcode',
            new_name='company_bpcode',
        ),
    ]
