# Generated by Django 6.0.1 on 2026-01-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_company_bfaxpcode_company_company_bpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_active',
            field=models.SmallIntegerField(default=True),
        ),
    ]
