# Generated by Django 6.0.1 on 2026-01-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_company_company_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency_deci',
            field=models.SmallIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
