# Generated by Django 6.0.1 on 2026-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_company_company_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency_deci',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
