# Generated by Django 6.0.1 on 2026-01-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_companysale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysale',
            options={'verbose_name': 'CompanySale', 'verbose_name_plural': 'CompanySales'},
        ),
    ]
